events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        # รองรับทั้ง IP ปัจจุบัน, Localhost และเครื่องอื่นๆ
        server_name 172.20.56.78 localhost;

        client_max_body_size 100M;
        proxy_read_timeout 600s;

        # 1. ให้บริการ Frontend Files (ชี้ไปที่โฟลเดอร์ dist ที่ Build แล้ว)
        location / {
            root "c:/Uni_Work'/3_1/Img_pro_code/Main/Image_Project/frontend/luma-frontend/dist";
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # 2. ส่งต่อคำขอ API ไปหา Flask Backend (Port 5000)
        location /api/ {
            proxy_pass http://127.0.0.1:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}